version: '3.2'

services:
    trender:
        depends_on:
            - db
        build: ./trender
        volumes: 
            - ./trender:/app/trender
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true
        #command: /usr/local/bin/gunicorn scrubber.wsgi -w 2 -b :8000 --reload
        command: python manage.py runserver 0.0.0.0:8000

    db:
        image: postgres:13
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: trender
            POSTGRES_DB: trender
        volumes:
            - trender:/var/lib/postgresql/data

    redis:
        image: redis:6.2.1
        expose:
            - "6379"

volumes:
    trender:


